---
name: Documentation Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/docs-lint.yaml'
      - 'docs/**'

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: .go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make docs-lint

  save-artifacts-on-fail:
    needs: [ docs-lint ]
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    needs: [ docs-lint ]
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
