---
name: GoLang Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/golint.yaml'
      - 'vendor/**'
      - '**.go'

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: .go-version
      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: 'v1.64.8'
          args: -v

  save-artifacts-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: hashicorp/terraform-provider-azuread/.github/workflows/save-artifacts.yaml@latest
    # uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: hashicorp/terraform-provider-azuread/.github/workflows/comment-failure.yaml@latest
    # uses: ./.github/workflows/comment-failure.yaml
