---
name: GoLang Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/golint.yaml'
      - 'vendor/**'
      - '**.go'

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: .go-version
      - uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4.0.1
        with:
          version: 'v1.64.8'
          args: -v

  save-artifacts-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml@latest
