---
name: GoLang Linting
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/golint.yaml'
      - 'vendor/**'
      - '**.go'

jobs:
  golint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: .go-version
      - uses: golangci/golangci-lint-action@d6238b002a20823d52840fda27e2d4891c5952dc # v4.0.1
        with:
          version: 'v1.64.8'
          args: -v

  save-artifacts-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: hashicorp/terraform-provider-azuread/.github/workflows/save-artifacts.yaml@latest

  comment-on-fail:
    needs: golint
    if: ${{ failure() }}
    uses: hashicorp/terraform-provider-azuread/.github/workflows/comment-failure.yaml@latest
