---
name: Unit Tests

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/unit-test.yaml'
      - 'vendor/**'
      - '**.go'

concurrency:
  group: 'unit-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  test:
    runs-on: custom-linux-large
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make test
        env:
          GITHUB_ACTIONS_STAGE: "UNIT_TESTS"

  save-artifacts-on-fail:
    needs: [ test ]
    if: ${{ failure() }}
    uses: ./.github/workflows/save-artifacts.yaml

  comment-on-fail:
    needs: [ test ]
    if: ${{ failure() }}
    uses: ./.github/workflows/comment-failure.yaml
